global using AutoMapper;
global using Microsoft.AspNetCore.Mvc;
global using Microsoft.EntityFrameworkCore;
global using AluraChallengeBackEnd.Data.Context;
global using AluraChallengeBackEnd.Api.ViewModels;
global using System.ComponentModel.DataAnnotations;
global using AluraChallengeBackEnd.Domain.Entities;
global using AluraChallengeBackEnd.Data.Repositories;
global using AluraChallengeBackEnd.Domain.Interfaces;