global using FluentValidation;
global using FluentValidation.Results;
global using AluraChallengeBackEnd.Core.Data;
global using AluraChallengeBackEnd.Domain.DTOs;
global using AluraChallengeBackEnd.Domain.Entities;
global using AluraChallengeBackEnd.Domain.Interfaces;
global using AluraChallengeBackEnd.Core.DomainObjects;
global using AluraChallengeBackEnd.Domain.Notifications;
global using AluraChallengeBackEnd.Domain.Entities.Validations;