global using Xunit;
global using Xunit.Sdk;
global using System.Net;
global using Xunit.Abstractions;
global using Microsoft.AspNetCore.Hosting;
global using Microsoft.AspNetCore.Mvc.Testing;
global using AluraChallengeBackEnd.Domain.Entities;
global using AluraChallengeBackEnd.Api.Tests.Config;
global using AluraChallengeBackEnd.Api.Tests.Attributes;
